Added correct license and updated author names
MDAnalysis/hole2-mdakit pull request #10
Opened 2023-02-08 19:16 UTC by ianmkenney

- Changed the license to be GPLv3 (#8)
- Tracked down author names from previous MDAnalysis commits to AUTHORS that weren't obvious from git blame

2023-02-08 19:26 UTC, ianmkenney commented
@IAlibay the issue was just with the license file being v2 right?

2023-02-09 00:08 UTC, orbeckst approved these changes
ok

2023-02-09 00:39 UTC, IAlibay requested changes
sorry for the quick review - please update the relevant classifiers in setup & pyproject files?

2023-02-10 17:28 UTC, IAlibay requested changes
So by updating the license to GPLv3 we'll also have to update the headers to state that they are GPLv3+ such as: https://github.com/MDAnalysis/hole2-mdakit/blob/1908af6c3decdd8efd9ed41b3de83add45adac38/mdakithole2/analysis/hole.py#L8

2023-02-10 18:04 UTC, IAlibay requested changes

2023-02-10 18:04 UTC, IAlibay commented on setup.py
> +    license='GNU Public License v3',
```suggestion
    license='GNU Public License v3+',
```
?

2023-02-10 18:08 UTC, ianmkenney commented on setup.py
> +    license='GNU Public License v3',
Done

2023-02-10 18:08 UTC, IAlibay approved these changes

2023-02-10 18:13 UTC, merged