Update installation instructions
MDAnalysis/hole2-mdakit pull request #63
Opened 2024-12-13 14:04 UTC by RubenChM

Fixes [#25](https://github.com/MDAnalysis/mdahole2/issues/25), [#55](https://github.com/MDAnalysis/mdahole2/issues/55)

Changes made in this Pull Request:

 - Update the installation part in readme and getting started to include conda with and without hole2.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2025-03-09 18:45 UTC, IAlibay commented
@lilyminium, if possible, could you triage this as the person in charge of mdahole2?

2025-03-14 05:52 UTC, lilyminium requested changes
Apologies for missing this @RubenChM -- it completely slipped by me! Largely looks great, the one minor quibble I have with all the conda commands is a preference to use the more common `-c channel` syntax instead of `::`.

Since this is your first contribution to mdahole2 could you please also add yourself to [authors](https://github.com/MDAnalysis/mdahole2/blob/main/AUTHORS.md)?

2025-03-14 05:52 UTC, lilyminium commented on README.md
> +conda install conda-forge::mdahole2
```suggestion
conda install -c conda-forge mdahole2
```

IMO this is more common syntax

2025-03-14 05:52 UTC, lilyminium commented on README.md
> +In case you want to use an already installed version of [hole2](https://www.holeprogram.org/) built from [source](https://github.com/osmart/hole2) or by installing it from conda (`conda install conda
```suggestion
In case you want to use an already installed version of [hole2](https://www.holeprogram.org/) built from [source](https://github.com/osmart/hole2) or by installing it from conda (`conda install -c conda-forge hole2`), you can use a version without `hole2` as dependency:
```

2025-03-14 05:52 UTC, lilyminium commented on README.md
> +conda install conda-forge::mdahole2-base
```suggestion
conda install -c conda-forge mdahole2-base
```

2025-03-14 05:52 UTC, lilyminium commented on docs/source/getting_started.rst
> +    conda install conda-forge::mdahole2
```suggestion
    conda install -c conda-forge mdahole2
```

2025-03-14 05:52 UTC, lilyminium commented on docs/source/getting_started.rst
> +    conda install conda-forge::mdahole2-base
```suggestion
    conda install -c conda-forge mdahole2-base
```

2025-03-14 09:37 UTC, RubenChM commented
Hey @lilyminium ! No problem for the delay. I am used to using -c too so is not a problem changing it. Hope is all good now.

2025-03-14 13:59 UTC, lilyminium approved these changes
Excellent, LGTM -- thanks so much @RubenChM for the improvements to our docs!

2025-03-14 14:00 UTC, merged